<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.9.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\MageekCore\MageekCore.csproj" />
    <ProjectReference Include="..\Core\PlaziatTools\PlaziatTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="fra.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
