name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: |
          dotnet nuget locals all --clear
          dotnet restore VsProject/MaGeek.sln --runtime win-x64
          msbuild "D:\a\MaGeek\MaGeek\VsProject\MaGeek.sln" /t:Rebuild /p:Configuration=Release
      - name: Gather
        run: |
          $mergedOutputDir = "D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs"
          $sourceDirs = @(
              "D:\a\MaGeek\MaGeek\VsProject\Core\MageekServer\bin\Release",
              "D:\a\MaGeek\MaGeek\VsProject\Apps\MageekDesktopClient\bin\Release",
              "D:\a\MaGeek\MaGeek\VsProject\Apps\MageekDesktopServer\bin\Release"
          )
          mkdir $mergedOutputDir -Force
          foreach ($sourceDir in $sourceDirs) {
              robocopy $sourceDir $mergedOutputDir /E
              # Check for errors
              if ($LASTEXITCODE -gt 7) {
                  Write-Error "Robocopy failed for $sourceDir with exit code $LASTEXITCODE"
                  exit $LASTEXITCODE
              }
          }
          Compress-Archive -Path "$mergedOutputDir\*" -DestinationPath "$mergedOutputDir.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of MaGeek"
          draft: false
          prerelease: false

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs.zip
          asset_name: MaGeek.zip
          asset_content_type: application/zip