name: Build and Publish

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Output 1
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication

      - name: Output 2
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication\Server

      - name: Output 3
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication\Client

      - name: Publish Server
        run: |
          dotnet publish VsProject\Core\MageekServer\MageekServer.csproj -p:PublishProfile=VsProject\Core\MageekServer\Properties\PublishProfiles\FolderProfile.pubxml -o D:\a\MaGeek\MaGeek\Publication\Server
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Publish Client
        run: |
          dotnet publish VsProject\Apps\MageekDesktopClient\MageekDesktopClient.csproj -p:PublishProfile=VsProject\Apps\MageekDesktopClient\Properties\PublishProfiles\FolderProfile.pubxml -o D:\a\MaGeek\MaGeek\Publication\Client
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Inspect
        run: |
          Get-ChildItem -Path D:\a\MaGeek\MaGeek -Recurse

      - name: Zip
        run: |
          Compress-Archive -Path D:\a\MaGeek\MaGeek\Publication\* -DestinationPath D:\a\MaGeek\MaGeek\Publication.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of MaGeek"
          draft: false
          prerelease: false

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\MaGeek\MaGeek\Publication.zip
          asset_name: MaGeek.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
