name: Publish Release on Main Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore NuGet packages
      run: nuget restore VsProject/MaGeek.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Build the solution, including the Installer project
    - name: Build Solution with Installer
      run: |
        msbuild VsProject/MaGeek.sln /t:Rebuild /p:Configuration=Release

    # Publish the build artifacts (optional)
    - name: Publish Artifacts
      run: |
        echo "Solution built successfully. Extracting setup files..."

  release:
    needs: build
    runs-on: windows-latest

    steps:
    # Checkout the repository again to upload release assets
    - name: Checkout code
      uses: actions/checkout@v3

    # Automatically create a new GitHub release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: "Release v1.0.${{ github.run_number }}"
        body: "Automated release of the .NET app setup files."
        draft: false
        prerelease: false

    # Upload setup files (e.g., .msi, .exe) from the Installer project
    - name: Upload Setup Files
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./VsProject/Utils/MageekSetup/Release/setup/MageekSetup.msi  # Path to .msi
        asset_name: setup.msi
        asset_content_type: application/octet-stream

    - name: Upload EXE File (if present)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./VsProject/Utils/MageekSetup/Release/setup.exe  # Path to .exe (optional)
        asset_name: setup.exe
        asset_content_type: application/octet-stream
