name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout 1
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear

      - name: Restore Packages
        run: |
          dotnet restore VsProject/MaGeek.sln --runtime win-x64

      - name: Build Solution
        run: |
          msbuild "D:\a\MaGeek\MaGeek\VsProject\MaGeek.sln" /t:Rebuild /p:Configuration=Release

      - name: Create Merged Output Directory
        run: |
          mkdir D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs

      - name: Copy Server Output
        run: |
          robocopy D:\a\MaGeek\MaGeek\VsProject\Core\MageekServer\bin\Release D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs /E
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Copy Desktop Client Output
        run: |
          robocopy D:\a\MaGeek\MaGeek\VsProject\Apps\MageekDesktopClient\bin\Release D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs /E
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Copy Desktop Server Output
        run: |
          robocopy D:\a\MaGeek\MaGeek\VsProject\Apps\MageekDesktopServer\bin\Release D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs /E
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout 2
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of the .NET app setup files."
          draft: false
          prerelease: false

      - name: Wait for Build Artifacts
        run: |
          sleep 2 # Wait for a few seconds

      - name: Upload Merged Output Files
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs
          asset_name: MergedOutputs.zip
          asset_content_type: application/zip