name: Build and Publish

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Output 1
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication

      - name: Output 2
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication\Server

      - name: Output 3
        run: |
          mkdir D:\a\MaGeek\MaGeek\Publication\Client

      - name: Publish Server
        run: |
          dotnet publish VsProject\Core\MageekServer\MageekServer.csproj -p:PublishProfile=VsProject\Core\MageekServer\Properties\PublishProfiles\FolderProfile.pubxml
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Publish Client
        run: |
          dotnet publish VsProject\Core\MageekServer\MageekDesktopClient.csproj -p:PublishProfile=VsProject\Apps\MageekDesktopClient\Properties\PublishProfiles\FolderProfile.pubxml
          if ($LASTEXITCODE -le 1) { exit 0 } else { exit $LASTEXITCODE }

      - name: Inspect
        run: |
          Get-ChildItem -Path D:\a\MaGeek\MaGeek -Recurse

      - name: MageekServer
        run: |
          robocopy D:\a\MaGeek\MaGeek\VsProject\Core\MageekServer\bin\Release\net8.0\publishLocal D:\a\MaGeek\MaGeek\Publication\Server /E
          if ($LASTEXITCODE -le 8) { exit 0 } else { exit $LASTEXITCODE }

      - name: MageekDesktopClient
        run: |
          robocopy D:\a\MaGeek\MaGeek\VsProject\Apps\MageekDesktopClient\bin\Release\net8.0-windows7.0\publish\win-x86 D:\a\MaGeek\MaGeek\Publication\Client /E
          if ($LASTEXITCODE -le 8) { exit 0 } else { exit $LASTEXITCODE }

      - name: Zip
        run: |
          Compress-Archive -Path D:\a\MaGeek\MaGeek\Publication\* -DestinationPath D:\a\MaGeek\MaGeek\Publication.zip

      # - name: Check Token
        # run: |
          # curl -H "Authorization: token ${{ secrets.DEPLOYTOKEN }}" https://api.github.com/user/repos
        # env:
          # DEPLOYTOKEN: ${{ secrets.DEPLOYTOKEN }}  # Ensure to use the correct secret name

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of MaGeek"
          draft: false
          prerelease: false

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: D:\a\MaGeek\MaGeek\VsProject\bin\Release\MergedOutputs.zip
          asset_name: MaGeek.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYTOKEN }}  # Use the default GITHUB_TOKEN
